file_format: "1"
id: LATIN
name: LATIN
type: shield
url: https://github.com
requires: [seeeduino_xiao_ble]
features:
  - keys
siblings:
  - LATIN
physical_layouts:
  - id: default
    name: Default Layout
    layout:
      width: 500
      height: 400
      keys:
        - width: 100
          height: 100
          x: 0
          y: 0
        - width: 100
          height: 100
          x: 100
          y: 0
        - width: 100
          height: 100
          x: 200
          y: 0
        - width: 100
          height: 100
          x: 300
          y: 0
        - width: 100
          height: 100
          x: 400
          y: 0
        - width: 100
          height: 100
          x: 0
          y: 100
        - width: 100
          height: 100
          x: 100
          y: 100
        - width: 100
          height: 100
          x: 200
          y: 100
        - width: 100
          height: 100
          x: 300
          y: 100
        - width: 100
          height: 100
          x: 400
          y: 100
        - width: 100
          height: 100
          x: 0
          y: 200
        - width: 100
          height: 100
          x: 100
          y: 200
        - width: 100
          height: 100
          x: 200
          y: 200
        - width: 100
          height: 100
          x: 300
          y: 200
        - width: 100
          height: 100
          x: 400
          y: 200
        - width: 100
          height: 100
          x: 0
          y: 300
        - width: 100
          height: 100
          x: 100
          y: 300
        - width: 100
          height: 100
          x: 200
          y: 300
        - width: 100
          height: 100
          x: 300
          y: 300
        - width: 100
          height: 100
          x: 400
          y: 300
