CONFIG_ZMK_USB=y
CONFIG_ZMK_HID=y
CONFIG_ZMK_WEBUSB=y
CONFIG_ZMK_USB_REMOTE_KSCAN=y
CONFIG_ZMK_BLE=n
CONFIG_ZMK_USB_LOGGING=y
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_CDC_ACM=y
CONFIG_USB_CDC_ACM_RINGBUF_SIZE=512
CONFIG_ZMK_POINTING=y